# Generated by Django 4.2.29 on 2026-03-06 16:18

from django.db import migrations, models
import django.db.models.deletion
import elections.models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_candidate_motto_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('org_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('HIGH_SCHOOL', 'High School'), ('GOVERNMENT', 'Government'), ('CORPORATE', 'Corporate'), ('COMMUNITY', 'Community'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('join_code', models.CharField(default=elections.models.generate_join_code, max_length=8, unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Voter'), ('ADMIN', 'Admin'), ('ORG_OWNER', 'Organization Owner'), ('SUPERUSER', 'Superuser')], default='USER', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='elections.organization'),
        ),
        migrations.AddField(
            model_name='election',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elections', to='elections.organization'),
        ),
    ]
